### ISSUE TITLE
Place Order stuck won't proceed further

### ISSUE THREAD

**Issue by gerryzqx** [ayushyamitabh/PizzaOrderSystem#3]
![screen shot 2018-05-10 at 9 50 50 am](https://user-images.githubusercontent.com/14956377/39873089-f8eb8f3e-5437-11e8-97f7-91807b0011ed.jpg)
![screen shot 2018-05-10 at 9 50 59 am](https://user-images.githubusercontent.com/14956377/39873091-f8f6590a-5437-11e8-88e0-6b5bd35082cd.jpg)

**Comment by ayushyamitabh** [comment]
Changed code to account for no drawings
```jsx
// CustomerHome.js Line 656
const imgDataUrls = this.state.customizedImages? this.state.customizedImages:{};
```

Will create new build with fix
